"""add an attribute to Moon class

Revision ID: 8c9538aa924a
Revises: 30e1d666022d
Create Date: 2025-11-04 11:45:07.342717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c9538aa924a'
down_revision = '30e1d666022d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moon', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
